function points = radar_points_to_table(pointStructs)
%RADAR_POINTS_TO_TABLE Convert decoded point structs to a MATLAB table.

if isempty(pointStructs)
    points = table( ...
        zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
        "VariableNames", ["angle_deg", "distance_mm", "sequence"]);
    return;
end

points = table( ...
    [pointStructs.angle_deg].', ...
    [pointStructs.distance_mm].', ...
    [pointStructs.sequence].', ...
    "VariableNames", ["angle_deg", "distance_mm", "sequence"]);
end
