function counters = radar_init_counters()
%RADAR_INIT_COUNTERS Create parser counter struct.

counters = struct( ...
    "valid_frames", 0, ...
    "crc_drops", 0, ...
    "sync_drops", 0, ...
    "timeout_readings", 0);
end
