function build_radar_model()
%BUILD_RADAR_MODEL Programmatically build radar_distributed.slx.
%   The model mirrors the report's architecture diagram end to end:
%
%   Node 1 (Arduino Uno)        UART          Node 2 (Jetson Nano)    Output
%   Sweep + HC-SR04 scene  -> XTEA/CRC16 -> EMI channel -> parse/decrypt
%        -> MTI tracker -> PPI display + ESC/POS virtual thermal printer
%
%   Run this once, then use run_demo to simulate.

mdl     = 'radar_distributed';
thisDir = fileparts(mfilename('fullpath'));
addpath(thisDir);

if bdIsLoaded(mdl)
    close_system(mdl, 0);
end
slxFile = fullfile(thisDir, [mdl '.slx']);
if exist(slxFile, 'file')
    delete(slxFile);
end

new_system(mdl);
set_param(mdl, ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', '0.04', ...          % one telemetry frame per 40 ms, as in firmware
    'StopTime', '16', ...             % ~2 full bidirectional cycles
    'InitFcn', sprintf('addpath(''%s''); radar_sim_reset;', thisDir));

mfcn = 'simulink/User-Defined Functions/MATLAB Function';

% --- Node 1: sensor node ------------------------------------------------
add_block('simulink/Sources/Clock', [mdl '/Clock'], ...
    'Position', [40 233 70 257]);

add_block(mfcn, [mdl '/Sweep and Scene'], 'Position', [150 205 290 285]);
set_mfcn_script(mdl, 'Sweep and Scene', strjoin({ ...
    'function [angle, dist] = sweep_scene(t)', ...
    '% Servo triangle sweep, 2 deg per 40 ms step (sketch_may7d timing),', ...
    '% plus the simulated HC-SR04 echo from the tabletop target scene.', ...
    'coder.extrinsic(''radar_scene'');', ...
    'step = floor(t / 0.04);', ...
    'phase = mod(step * 2, 360);', ...
    'if phase <= 180', ...
    '    angle = phase;', ...
    'else', ...
    '    angle = 360 - phase;', ...
    'end', ...
    'dist = 0;', ...
    'dist = radar_scene(angle, t);', ...
    'end'}, newline));

add_block(mfcn, [mdl '/XTEA CRC16 Framing'], 'Position', [370 205 510 285]);
set_mfcn_script(mdl, 'XTEA CRC16 Framing', strjoin({ ...
    'function frame = security_framing(angle, dist)', ...
    '% TaskSecurity equivalent: XTEA-encrypted 12-byte telemetry frame.', ...
    'coder.extrinsic(''radar_build_frame'');', ...
    'frame = zeros(12, 1);', ...
    'frame = radar_build_frame(angle, dist);', ...
    'end'}, newline));

% --- UART channel -------------------------------------------------------
add_block('simulink/Sources/Constant', [mdl '/EMI Injection'], ...
    'Value', '0', 'Position', [370 330 430 360]);

add_block(mfcn, [mdl '/UART Channel'], 'Position', [590 215 730 305]);
set_mfcn_script(mdl, 'UART Channel', strjoin({ ...
    'function rx = uart_channel(txf, noise_on)', ...
    '% 115200-baud link; EMI Injection = 1 flips random bits (Metric 1).', ...
    'coder.extrinsic(''radar_channel'');', ...
    'rx = zeros(12, 1);', ...
    'rx = radar_channel(txf, noise_on);', ...
    'end'}, newline));

% --- Node 2: edge node --------------------------------------------------
add_block(mfcn, [mdl '/Frame Parser Decrypt'], 'Position', [810 195 960 315]);
set_mfcn_script(mdl, 'Frame Parser Decrypt', strjoin({ ...
    'function [valid, angle, dist, validCnt, crcDrops] = edge_parser(rx)', ...
    '% Backend FrameParser equivalent: sync + CRC check, XTEA decrypt.', ...
    'coder.extrinsic(''radar_parse_frame'');', ...
    'valid = 0; angle = 0; dist = 0; validCnt = 0; crcDrops = 0;', ...
    '[valid, angle, dist, validCnt, crcDrops] = radar_parse_frame(rx);', ...
    'end'}, newline));

add_block(mfcn, [mdl '/MTI Tracker'], 'Position', [1040 195 1190 315]);
set_mfcn_script(mdl, 'MTI Tracker', strjoin({ ...
    'function [sweeps, cycles, nvec, cycleDone] = mti_tracker(valid, angle, dist, t)', ...
    '% SweepBuilder + nearest-neighbor MTI (backend mti_cpu equivalent).', ...
    'coder.extrinsic(''radar_mti_step'');', ...
    'sweeps = 0; cycles = 0; nvec = 0; cycleDone = 0;', ...
    '[sweeps, cycles, nvec, cycleDone] = radar_mti_step(valid, angle, dist, t);', ...
    'end'}, newline));

add_block(mfcn, [mdl '/PPI Display'], 'Position', [1040 390 1190 470]);
set_mfcn_script(mdl, 'PPI Display', strjoin({ ...
    'function ppi_display(angle, valid, dist, cycleDone)', ...
    '% Live half-PPI preview (stand-in for the Vulkan renderer).', ...
    'coder.extrinsic(''radar_ppi_draw'');', ...
    'radar_ppi_draw(angle, valid, dist, cycleDone);', ...
    'end'}, newline));

% --- Output: thermal printer -------------------------------------------
add_block(mfcn, [mdl '/ESCPOS Thermal Printer'], 'Position', [1280 225 1430 285]);
set_mfcn_script(mdl, 'ESCPOS Thermal Printer', strjoin({ ...
    'function nbytes = thermal_printer(cycleDone)', ...
    '% Stage 5: on each completed bidirectional cycle, rasterize the PPI,', ...
    '% encode real ESC/POS bytes, and send them to the virtual printer.', ...
    'coder.extrinsic(''radar_escpos_encode'', ''radar_virtual_printer'');', ...
    'nbytes = 0;', ...
    'if cycleDone > 0.5', ...
    '    b = radar_escpos_encode();', ...
    '    nbytes = radar_virtual_printer(b);', ...
    'end', ...
    'end'}, newline));

% --- Telemetry displays -------------------------------------------------
displays = { ...
    'Valid Frames',  [1040  90 1130 120]; ...
    'CRC Drops',     [1160  90 1250 120]; ...
    'Sweeps',        [1280  90 1370 120]; ...
    'Cycles',        [1400  90 1490 120]; ...
    'MTI Vectors',   [1520  90 1610 120]; ...
    'Printed Bytes', [1520 240 1610 270]};
for k = 1:size(displays, 1)
    add_block('simulink/Sinks/Display', [mdl '/' displays{k, 1}], ...
        'Position', displays{k, 2});
end

% --- Wiring -------------------------------------------------------------
lines = { ...
    'Clock/1',                 'Sweep and Scene/1'; ...
    'Clock/1',                 'MTI Tracker/4'; ...
    'Sweep and Scene/1',       'XTEA CRC16 Framing/1'; ...
    'Sweep and Scene/2',       'XTEA CRC16 Framing/2'; ...
    'XTEA CRC16 Framing/1',    'UART Channel/1'; ...
    'EMI Injection/1',         'UART Channel/2'; ...
    'UART Channel/1',          'Frame Parser Decrypt/1'; ...
    'Frame Parser Decrypt/1',  'MTI Tracker/1'; ...
    'Frame Parser Decrypt/2',  'MTI Tracker/2'; ...
    'Frame Parser Decrypt/3',  'MTI Tracker/3'; ...
    'Frame Parser Decrypt/2',  'PPI Display/1'; ...
    'Frame Parser Decrypt/1',  'PPI Display/2'; ...
    'Frame Parser Decrypt/3',  'PPI Display/3'; ...
    'Frame Parser Decrypt/4',  'Valid Frames/1'; ...
    'Frame Parser Decrypt/5',  'CRC Drops/1'; ...
    'MTI Tracker/1',           'Sweeps/1'; ...
    'MTI Tracker/2',           'Cycles/1'; ...
    'MTI Tracker/3',           'MTI Vectors/1'; ...
    'MTI Tracker/4',           'PPI Display/4'; ...
    'MTI Tracker/4',           'ESCPOS Thermal Printer/1'; ...
    'ESCPOS Thermal Printer/1', 'Printed Bytes/1'};
for k = 1:size(lines, 1)
    add_line(mdl, lines{k, 1}, lines{k, 2}, 'autorouting', 'on');
end

% --- Annotations marking the architecture domains -----------------------
try
    notes = { ...
        'NODE 1: SENSOR NODE (Arduino Uno + FreeRTOS, hard real-time)', [150 160]; ...
        'UART 115200 baud, 12-byte XTEA+CRC16 frames',                  [590 170]; ...
        'NODE 2: EDGE NODE (Jetson Nano, C++ backend)',                 [810 160]; ...
        'OUTPUT: 58mm THERMAL PRINTER (ESC/POS over USB)',              [1280 190]};
    for k = 1:size(notes, 1)
        a = Simulink.Annotation(mdl, notes{k, 1});
        a.Position = notes{k, 2};
        a.FontSize = 10;
        a.FontWeight = 'bold';
    end
catch
    % annotations are cosmetic; ignore API differences
end

save_system(mdl, slxFile);
fprintf('Built %s\n', slxFile);
end

function set_mfcn_script(mdl, blockName, script)
chart = find(sfroot, '-isa', 'Stateflow.EMChart', 'Path', [mdl '/' blockName]);
assert(~isempty(chart), 'MATLAB Function block not found: %s', blockName);
chart.Script = script;
end
