function radar_sim_reset()
%RADAR_SIM_RESET Initialize shared simulation state.
%   Called automatically by the model InitFcn callback before every run.
%   All cross-block state (sweep buffers, MTI vectors, protocol counters)
%   lives in the global RADAR_SIM struct so blocks stay thin wrappers.

global RADAR_SIM

here = fileparts(mfilename('fullpath'));
printDir = fullfile(here, 'prints');
if ~exist(printDir, 'dir')
    mkdir(printDir);
end

RADAR_SIM = struct( ...
    'tau_mm',            80, ...        % MTI nearest-neighbor threshold (matches backend --tau-mm)
    'vector_draw_scale', 3, ...         % arrows scaled x3 for legibility
    'max_range_mm',      800, ...       % 80 cm tabletop arena (report Sec. 7)
    'headless',          batchStartupOptionUsed, ...
    'prevAngle',         NaN, ...
    'dir',               0, ...
    'buf',               zeros(0, 2), ...   % current sweep [angle_deg, dist_mm]
    'lastFwd',           zeros(0, 2), ...   % clustered targets, cartesian mm
    'lastRet',           zeros(0, 2), ...
    'vectors',           zeros(0, 4), ...   % [x1 y1 x2 y2] per matched target
    'sweepCount',        0, ...
    'cycleCount',        0, ...
    'validCnt',          0, ...
    'crcDrops',          0, ...
    'timeouts',          0, ...
    'printDir',          printDir);
end
